name: Spec
description: Hidden spectator mode for moderators
version: '1.2.0'
main: xd.firewolfik.spec.Main
api-version: '${plugin.api-version}'
load: POSTWORLD
softdepend: [Essentials]
authors: [firewolfik]
commands:
  spec:
    usage: /spec <player>|alerts|reload
permissions:
  spec.use:
    default: op
  spec.any:
    default: op
  spec.reload:
    default: op
